### ISSUE TITLE
Supabase RLS query error

### ISSUE THREAD

**Issue by flowscience** [oceanprotocol/tokengated-next-chatgpt#24]
**Describe the bug**
`Failed to run sql query: relation "public.users" does not exist`

**To Reproduce**
1. Follow instructions to deploy Vercel app
2. Create public.users table with `id` column linked to `auth.users.id`
![image](https://github.com/oceanprotocol/tokengated-next-chatgpt/assets/10070465/48c9116c-be63-4ef0-85ed-97a43f8867d5)
3. Run query in Supabase SQL Editor
![image](https://github.com/oceanprotocol/tokengated-next-chatgpt/assets/10070465/0e8bd398-cb66-4f11-a6f8-e5b66c59d539)
 
**Expected behavior**
Setup Supabase Role Level Security (RLS)

**Screenshots**

**Desktop:**
 - OS: Windows 10 Home
 - Brave
 - Version 1.52.130

**Additional context**

**Comment by idiom-bytes** [comment]
I believe you named your table `public users` rather than creating a Users table, inside the public schema. Giving you a `public.users` table.

Can you try again?

I will adjust the language of the README.md

**Comment by flowscience** [comment]
Worked! Thanks!
